appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: lcJ2JGf76WD+Xitp735bSYYxX35MnRITc2L2D8cmv38jeXOEW16pPK9XyV4lIxklfiUJFlZMk4MkbUj6pcwvFRjFwBHodn9pBWI0+Yzyi2S0+KpaCYq+bDDdPSmKUQOfbemyNC1gjlV9l8zweoNxbB7B7Nm8nhiNdtyhwV55Z7J9NHvneUGu7sAG+hlOMJEnGuUrjCVnJ49m6CI5VjxiNFDhbNMslQlm7HaQISA6Nt4Irbf20hdeVFRfo1VgUllqMm2XOluKoQOkX1lzqHB0Igrlg5d6hOpsXx0vxw0OsZDkljb1mlebOJfIiDedrJtFThtq0W92hyTlh4MOgJXXIx0gn9uELFqhohcfQezaL3bQq0ICC5ZFpq7lGA19LZCurjHRBytTQOJY/I3Ex/ADA6Md5A4tU/b9XbfNAXRZe4FCjI7jEltuwFbZhfNxXIdd7Z57Vr60GGFYgZIPdm07cN9CRXtIejmEV8V9XbS6sx65U8yscAjDgkpDsqKujBbTNMazAkvxtsUtTL2PvEr0zq+YgUir6llBIfgGlXqo+dZXoO5T32ixuoAthva2OriIS+6/TA/nAX5JtPO/Cyep+b8pjYXxAgc+p63hSy8QtGLYWTO7wTYV4B2whIT7fyrVwmEsy2xg3SYmG5u+bQQEykRqv4SUv/wz6vQpSJA4hVI=
conda_forge_output_validation: true
